
FROM ubuntu:stonking
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y cmake \
    && apt-get install libboost1.90-dev\
    && apt-get install -y libasio-dev
